# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ICON'26
email: vincenzo.barbuto@dimes.unical.it
description: >-
  Website for the 1st ICON Workshop on IoT Applications and Cyber-Physical Systems
  in the Edge-Cloud Continuum (ICON 2026),
  co-located with the 24th IEEE International Symposium on Network Computing
  and Applications (NCA 2026),
  that will take place in Ortigia-Syracuse, Sicily, Italy, November 10-13, 2026.
baseurl: "/2026"
url: "https://workshop-icon.github.io"
#twitter_username: icon_workshop
#github_username:  workshop-icon

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - committees.md
  - program.md
  - weditions.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  quiet_deps: true
